name: dont_waste
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.15.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  flutter: 
    sdk: flutter
  sizer: ^2.0.15
  google_fonts: ^2.2.0
  firebase_core: 1.12.0
  cloud_firestore: 3.1.8
  google_maps_flutter: ^2.1.1
  firebase_auth: 3.3.7
  permission_handler: ^9.1.0
  geocoding: ^2.0.2
  url_launcher: ^6.0.20
  firebase_storage: ^10.2.9
  image_picker: ^0.8.4+11
  uuid: ^3.0.6
  easy_localization: ^3.0.0
  geoflutterfire: ^3.0.3
  geolocator: ^8.2.0
  shared_preferences: ^2.0.13
  firebase_messaging: ^11.4.1

dev_dependencies: 
  flutter_lints: ^1.0.0
  lints: 1.0.1
  flutter_launcher_icons: ^0.9.2
  flutter_test: 
    sdk: flutter

flutter: 
  assets:
      - assets/images/burger.png
      - assets/images/lunch.png
      - assets/images/map.jpeg
      - assets/images/EN.png
      - assets/images/RU.png
      - assets/images/UZ.png
      - assets/langs/uz-UZ.json
      - assets/langs/ru-RU.json
      - assets/langs/en-EN.json
      - assets/images/default-photo.png
      - assets/google-maps-style.json
      - assets/images/food-delivery.png
      - assets/images/customer-review.png
      - assets/images/chat.png
      - assets/images/operator.png
      - assets/images/icon.png
      - assets/images/payme.png
      - assets/images/click.png
      - assets/images/sad.gif
      - assets/images/avatar.png
      - assets/images/bell.gif
      - assets/images/discount.png
      - assets/images/coins.png
  uses-material-design: true
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
