name: dont_waste
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.15.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  flutter: 
    sdk: flutter
  sizer: ^2.0.15
  google_fonts: ^2.2.0
  firebase_core: ^1.12.0
  cloud_firestore: ^3.1.8
  google_maps_flutter: ^2.1.1
  firebase_auth: ^3.3.7
  permission_handler: ^9.1.0
  geocoding: ^2.0.2

dev_dependencies: 
  flutter_lints: ^1.0.0
  lints: 1.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  assets:
      - assets/images/burger.png
      - assets/images/lunch.png
      - assets/images/map.jpeg
  uses-material-design: true

